# Generated by Django 5.1.7 on 2025-03-12 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetGard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='streetgard/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreetGardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_dht', models.FloatField()),
                ('humidity_dht', models.FloatField()),
                ('temp_bmp', models.FloatField()),
                ('pressure_bmp', models.FloatField()),
                ('altitude_bmp', models.FloatField()),
                ('relativeheight_bmp', models.FloatField()),
                ('latitude_gsm', models.FloatField()),
                ('longitude_gsm', models.FloatField()),
                ('rainsensor', models.FloatField()),
                ('servo_state', models.BooleanField()),
                ('pir_state', models.BooleanField()),
                ('relay_state', models.BooleanField()),
                ('ldr_state', models.BooleanField()),
                ('bulb_state', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('streetgard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.streetgard')),
            ],
        ),
    ]
