# Generated by Django 5.1.7 on 2025-03-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streetgarddata',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
